---
title: "Assignment_02_Shoyeb_Khan_2021H1540806P"
author: "Shoyeb_Khan_2021H1540806P"
date: "02/10/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#1. Write a function that takes two numbers, a and b, as arguments, and returns a raised to the power b.

b_pow_a <- function(a,b)
               {return (b**a) ; }

#+ Challenge 1: Try to generate the numbers a and b randomly in the range of 1 to 10 as part of the function.
a <- sample(1:10,10)

b <- sample(1:10,10)

a # The value of a.

b # The value of b.

#+ Challenge 2: Initialize the number a as a vector and try to return a vector with each element of a raised to the number b.
b_pow_a(a,b)

#2. Write a function that takes a number as argument and returns true if it is divisible by 2, 3, 5, 7, 11, 13, and false otherwise.
    
#    + Challenge: Randomize the number that needs to be given as an argument to the function in the range from 1 to 1000.


divisiblity_check <- function(x)
{
  if(x %%2 || x%%3 || x%%5 || x%%7 || x%%11 || x%%13)
  {
    check_o <- "TRUE"
  }
  
  else 
    check_o <- "FALSE"
  
  return (check_o) ;
  
}


rand_num <- sample(1:1000,1000)
checker <- c()

for ( i in 1:1000){
checker[i] <-  divisiblity_check(rand_num[i])
  
}

#3. Write a function that takes a non-negative integer as its argument and returns its factorial.
#    + Challenge: Do not use the built-in function factorial()

factorial_num <- function(y)
{
   if ( y ==0 || y==1 )
     
        return(1)
  
   else 
         return (y*factorial_num(y-1))
  
   
   }

#4. Write a function to compute the dot product of two vectors.
#+ Challenge 1: Do not use in-built R functions.(Clue: Iterative algorithm)

dot_prod_func <- function(a,b)
{
  prod <- c()

  for (i in 1 :3) {
     prod[i] <- a[i] * b[i]
   }

  sum <- 0

  for (j in 1 :3) {
  sum <- sum + prod[i]
  }

  return(sum)
  
}


a <- c(1,2,3)
b <- c(4,5,9)

dot_prod_func(a,b)


#+ Challenge 2: Vectors should be of arbitrary length.

##Enter any arbitary number and store it in z_vector.

#z <- scan()
#z_p <- scan()

z   <- c(1,2,3,4,5)

z_p <- c(9,8,7,6,5)

dot_prod_arbi <- function(z,z_p){
  prod_arbi <- c()
  
  for(i in 1 : length(z)){
  prod_arbi[i] <- z[i]*z_p[i]
  }

  sum_arbi <- 0

  for (j in 1 :length(z)) {
  sum_arbi <- sum_arbi + prod_arbi[j]
  }
  
  return(sum_arbi)
  
}

sprintf("The dot product of two vectors z and z_p is : %d",dot_prod_arbi(z,z_p))

#5. Write a function that takes a numeric vector and prints on screen the mean and standard deviation.
#+ Challenge: Do not use in-built R functions.
#n <- readline()
#n <- as.integer(n)

n <- 10

data <- sample(1:n,n)

mean_sd_value <- function(data,n){
  sum_data <- 0

  for(i in 1:n){
  sum_data <- sum_data + data[i]
  }

  mean <- sum_data/10

  sprintf("The mean of the sample data is :%f",mean)
  
  ## Calculation of the Standard Deviations.

  diff_squ <- c()
  sum_diff <- c()

  sum_diff <- 0

  for(i in 1:n){
  diff_squ[i] <- (data[i] - mean)**2 
  sum_diff <- sum_diff + diff_squ[i]
  }

  variance <- sum_diff/(n-1)

  standard_dev <- sqrt(variance)

  sprintf("The standard deviation of the sample data is :%f",standard_dev)
  
}

mean_sd_value(data,n)

#6. Write a function given that takes a vector as its argument and returns a new vector with the elements of the first vector with #duplicated elements removed.   
#    + HINT: Iterate through the vector checking for duplicate elements.

vector_uni <- function(vector_dup)
{
  vector_undup <- c()

  for(i in 1:length(vector_dup))
    {
       if(sum(vector_dup[i]==vector_undup) == 0)
         { 
           vector_undup <- c(vector_undup,vector_dup[i])
     
         }
    }
  return (vector_undup)
  
}

vector_dup <- c(1,12,12,15,16,9,9,10,20,100,100,56)

vector_uni(vector_dup)

#7. Write a function to find out the factors of a positive integer. 
#+ Challenge: Find 2 different solutions. 
#+ HINT (For 1st solution): Look up the R documentation for functions such as `lapply`

factors_fun <- function(x){
  
  fact <- c()
  fact <- 0
  
  for(i in 1:x){
    if(x %% i == 0){
      fact[i] <- i 
    }
  }
  
  return (na.omit(fact))
  
}

list <- c(1,5,8,10,12)

lapply(list, factors_fun)


## 2 HINT (For 2nd solution): `Vectorize` and `Filter` functions may be of some help.

vector_fun <- Vectorize(factors_fun)

vector_fun(3)

#8. Write a function that prints out the value of the Ackermann Function after entering two numbers as input. (Picked up this problem because it # #reminds me of 'Attack on Titan', PS: It's an anime!)  

ackerman_func <- function(m,n){
  if(m == 0){
    n +1 
  }
  
  else if(m >0 && n ==0){
    ackerman_func(m-1,1)
  }
  
  else if(m > 0 && n > 0){
    ackerman_func(m-1,ackerman_func(m,n-1))
  }
  
}
ackerman_func(1,200)
ackerman_func(1,10)
ackerman_func(1,7)

```

